# requirements.yml
collections:
  - name: ansible.netcommon
    version: 7.2.0
  - name: cisco.nxos
    version: 10.0.0
  - name: cisco.ios
    version: 10.0.0
  - name: cisco.iosxr
    version: 11.0.0
  - name: cisco.meraki
    version: 2.21.1