- hosts: localhost
  gather_facts: false
  ignore_unreachable: true
  tasks:
  - name: run show control connections to gather evidence
    ignore_errors: true
    timeout: 3600
    poll: 10
    ios_command:
        commands: show control connections
    register: evidence_show_control_connections
  - name: run show control local-properties to gather evidence
    ignore_errors: true
    timeout: 3600
    poll: 10
    ios_command:
        commands: show control local-properties
    register: evidence_show_control_local_properties
  - name: run show run system to gather evidence
    ignore_errors: true
    timeout: 3600
    poll: 10
    ios_command:
        commands: show run system
    register: evidence_show_run_system
  - name: run show interface description | tab to gather evidence
    ignore_errors: true
    timeout: 3600
    poll: 10
    ios_command:
        commands: show interface description | tab
    register: evidence_show_interface_description___tab
  - name: run show interface | tab to gather evidence
    ignore_errors: true
    timeout: 3600
    poll: 10
    ios_command:
        commands: show interface | tab
    register: evidence_show_interface___tab
  - name: run show arp to gather evidence
    ignore_errors: true
    timeout: 3600
    poll: 10
    ios_command:
        commands: show arp
    register: evidence_show_arp
  - name: run show control summary to gather evidence
    ignore_errors: true
    timeout: 3600
    poll: 10
    ios_command:
        commands: show control summary
    register: evidence_show_control_summary
  - name: run show version to gather evidence
    ignore_errors: true
    timeout: 3600
    poll: 10
    ios_command:
        commands: show version
    register: evidence_show_version
  - name: run show hardware inventory | tab to gather evidence
    ignore_errors: true
    timeout: 3600
    poll: 10
    ios_command:
        commands: show hardware inventory | tab
    register: evidence_show_hardware_inventory___tab
  - name: run show system status to gather evidence
    ignore_errors: true
    timeout: 3600
    poll: 10
    ios_command:
        commands: show system status
    register: evidence_show_system_status
  - name: run show ospf neighbor to gather evidence
    ignore_errors: true
    timeout: 3600
    poll: 10
    ios_command:
        commands: show ospf neighbor
    register: evidence_show_ospf_neighbor
  - name: run show ip route to gather evidence
    ignore_errors: true
    timeout: 3600
    poll: 10
    ios_command:
        commands: show ip route
    register: evidence_show_ip_route
  - name: run show ip routes summary to gather evidence
    ignore_errors: true
    timeout: 3600
    poll: 10
    ios_command:
        commands: show ip routes summary
    register: evidence_show_ip_routes_summary
  - name: run show hardware real-time-information to gather evidence
    ignore_errors: true
    timeout: 3600
    poll: 10
    ios_command:
        commands: show hardware real-time-information
    register: evidence_show_hardware_real_time_information
  - name: run show ntp associations to gather evidence
    ignore_errors: true
    timeout: 3600
    poll: 10
    ios_command:
        commands: show ntp associations
    register: evidence_show_ntp_associations
  - name: run show omp peers to gather evidence
    ignore_errors: true
    timeout: 3600
    poll: 10
    ios_command:
        commands: show omp peers
    register: evidence_show_omp_peers
  - name: run show omp summary to gather evidence
    ignore_errors: true
    timeout: 3600
    poll: 10
    ios_command:
        commands: show omp summary
    register: evidence_show_omp_summary
  - name: run show omp routes to gather evidence
    ignore_errors: true
    timeout: 3600
    poll: 10
    ios_command:
        commands: show omp routes
    register: evidence_show_omp_routes
  - name: run show tunnel statistics to gather evidence
    ignore_errors: true
    timeout: 3600
    poll: 10
    ios_command:
        commands: show tunnel statistics
    register: evidence_show_tunnel_statistics
  - name: run show ntp status to gather evidence
    ignore_errors: true
    timeout: 3600
    poll: 10
    ios_command:
        commands: show ntp status
    register: evidence_show_ntp_status
  - name: run show tunnel statistics to gather evidence
    ignore_errors: true
    timeout: 3600
    poll: 10
    ios_command:
        commands: show tunnel statistics
    register: evidence_show_tunnel_statistics
  - name: run show ipsec inbound-connections to gather evidence
    ignore_errors: true
    timeout: 3600
    poll: 10
    ios_command:
        commands: show ipsec inbound-connections
    register: evidence_show_ipsec_inbound_connections
  - name: run show ipsec outbound-connections to gather evidence
    ignore_errors: true
    timeout: 3600
    poll: 10
    ios_command:
        commands: show ipsec outbound-connections
    register: evidence_show_ipsec_outbound_connections
  - name: run show bfd summary to gather evidence
    ignore_errors: true
    timeout: 3600
    poll: 10
    ios_command:
        commands: show bfd summary
    register: evidence_show_bfd_summary
  - name: run show bfd sessions to gather evidence
    ignore_errors: true
    timeout: 3600
    poll: 10
    ios_command:
        commands: show bfd sessions
    register: evidence_show_bfd_sessions
  - name: run show control connections-history to gather evidence
    ignore_errors: true
    timeout: 3600
    poll: 10
    ios_command:
        commands: show control connections-history
    register: evidence_show_control_connections_history
  - name: run show running-config to gather evidence
    ignore_errors: true
    timeout: 3600
    poll: 10
    ios_command:
        commands: show running-config
    register: evidence_show_running_config
  - name: run show logging to gather evidence
    ignore_errors: true
    timeout: 3600
    poll: 10
    ios_command:
        commands: show logging
    register: evidence_show_logging
  - name: run show system to gather evidence
    ignore_errors: true
    timeout: 3600
    poll: 10
    ios_command:
        commands: show system
    register: evidence_show_system
  - name: run show software to gather evidence
    ignore_errors: true
    timeout: 3600
    poll: 10
    ios_command:
        commands: show software
    register: evidence_show_software
  - name: run show clock to gather evidence
    ignore_errors: true
    timeout: 3600
    poll: 10
    ios_command:
        commands: show clock
    register: evidence_show_clock
  - name: run show policy from-vsmart to gather evidence
    ignore_errors: true
    timeout: 3600
    poll: 10
    ios_command:
        commands: show policy from-vsmart
    register: evidence_show_policy_from_vsmart
  - name: run show system statu to gather evidence
    ignore_errors: true
    timeout: 3600
    poll: 10
    ios_command:
        commands: show system statu
    register: evidence_show_system_statu
  - name: display evidence show control connections
    debug:
      var: evidence_show_control_connections["stdout_lines"][0]
  - name: display evidence show control local-properties
    debug:
      var: evidence_show_control_local_properties["stdout_lines"][0]
  - name: display evidence show run system
    debug:
      var: evidence_show_run_system["stdout_lines"][0]
  - name: display evidence show interface description | tab
    debug:
      var: evidence_show_interface_description_|_tab["stdout_lines"][0]
  - name: display evidence show interface | tab
    debug:
      var: evidence_show_interface_|_tab["stdout_lines"][0]
  - name: display evidence show arp
    debug:
      var: evidence_show_arp["stdout_lines"][0]
  - name: display evidence show control summary
    debug:
      var: evidence_show_control_summary["stdout_lines"][0]
  - name: display evidence show version
    debug:
      var: evidence_show_version["stdout_lines"][0]
  - name: display evidence show hardware inventory | tab
    debug:
      var: evidence_show_hardware_inventory_|_tab["stdout_lines"][0]
  - name: display evidence show system status
    debug:
      var: evidence_show_system_status["stdout_lines"][0]
  - name: display evidence show ospf neighbor
    debug:
      var: evidence_show_ospf_neighbor["stdout_lines"][0]
  - name: display evidence show ip route
    debug:
      var: evidence_show_ip_route["stdout_lines"][0]
  - name: display evidence show ip routes summary
    debug:
      var: evidence_show_ip_routes_summary["stdout_lines"][0]
  - name: display evidence show hardware real-time-information
    debug:
      var: evidence_show_hardware_real_time_information["stdout_lines"][0]
  - name: display evidence show ntp associations
    debug:
      var: evidence_show_ntp_associations["stdout_lines"][0]
  - name: display evidence show omp peers
    debug:
      var: evidence_show_omp_peers["stdout_lines"][0]
  - name: display evidence show omp summary
    debug:
      var: evidence_show_omp_summary["stdout_lines"][0]
  - name: display evidence show omp routes
    debug:
      var: evidence_show_omp_routes["stdout_lines"][0]
  - name: display evidence show tunnel statistics
    debug:
      var: evidence_show_tunnel_statistics["stdout_lines"][0]
  - name: display evidence show ntp status
    debug:
      var: evidence_show_ntp_status["stdout_lines"][0]
  - name: display evidence show tunnel statistics
    debug:
      var: evidence_show_tunnel_statistics["stdout_lines"][0]
  - name: display evidence show ipsec inbound-connections
    debug:
      var: evidence_show_ipsec_inbound_connections["stdout_lines"][0]
  - name: display evidence show ipsec outbound-connections
    debug:
      var: evidence_show_ipsec_outbound_connections["stdout_lines"][0]
  - name: display evidence show bfd summary
    debug:
      var: evidence_show_bfd_summary["stdout_lines"][0]
  - name: display evidence show bfd sessions
    debug:
      var: evidence_show_bfd_sessions["stdout_lines"][0]
  - name: display evidence show control connections-history
    debug:
      var: evidence_show_control_connections_history["stdout_lines"][0]
  - name: display evidence show running-config
    debug:
      var: evidence_show_running_config["stdout_lines"][0]
  - name: display evidence show logging
    debug:
      var: evidence_show_logging["stdout_lines"][0]
  - name: display evidence show system
    debug:
      var: evidence_show_system["stdout_lines"][0]
  - name: display evidence show software
    debug:
      var: evidence_show_software["stdout_lines"][0]
  - name: display evidence show clock
    debug:
      var: evidence_show_clock["stdout_lines"][0]
  - name: display evidence show policy from-vsmart
    debug:
      var: evidence_show_policy_from_vsmart["stdout_lines"][0]
  - name: display evidence show system statu
    debug:
      var: evidence_show_system_statu["stdout_lines"][0]
