- hosts: all
  gather_facts: true
  tasks:
    - name: run show version on remote devices
      register: show_control_connections
      ansible.netcommon.network_cli:
        commands:
          - show control connections
          - show control local-properties
    - name: show control connections
      debug: var=show_control_connections.stdout_lines
