- hosts: all
  gather_facts: true
  tasks:
    - name: run show version on remote devices
      register: show_control_connections
      command: show control connections
    - name: run show control local-properties
      register: show_control_local_properties
      command: show control local-properties






    - name: show control connections
      debug: var=show_control_connections.stdout_lines
    - name: show control local-properties
      debug: var=show_control_local_properties.stdout_lines
