---
- name: Network Getting Started First Playbook
  connection: ansible.netcommon.network_cli
  gather_facts: false
  hosts: all
  tasks:
    - name: RUN show version
      register: show_version
      ansible.netcommon.network_cli:
        commands:
          - show version
    - name: Display the show version output
      ansible.builtin.debug:
        var: show_version.stdout
